theme {
    color_scheme = /usr/share/color-schemes/Zephyrus.colors
    icon_theme = breeze-dark
    style = Fusion
    font = Noto Sans
    font_size = 11
    font_fixed = monospace
    font_fixed_size = 11
}
