general {
    hide_cursor = true
    immediate_render = true
}

background {
    monitor =
    color = rgba(1b2021ff)
    path = $ZEPHYRUS_LOCK_WALLPAPER
    blur_passes = 0
}

input-field {
    monitor =
    size = 280, 48
    position = 0, -40
    halign = center
    valign = center
    outline_thickness = 2
    rounding = 16
    outer_color = rgba(ff465cff)
    inner_color = rgba(272d2eff)
    font_color = rgba(e4daddff)
    fail_color = rgba(ff8090ff)
    check_color = rgba(ff465cff)
    placeholder_text = Password
}
