#!/usr/bin/env python3
"""Install a reversible development shim; never copy the repository configuration."""

import argparse
import hashlib
import json
import os
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from services.wallpaper import sync_lock_background


def fingerprint(path):
    if path.is_symlink():
        return "link:" + os.readlink(path)
    if path.is_file():
        return "file:" + hashlib.sha256(path.read_bytes()).hexdigest()
    return None


def install(config, state, root=ROOT):
    manifest = state / "zephyrus-shell/dev-session.json"
    files = {
        config / "hypr/hyprland.lua": "-- Generated by Zephyrus setup-session.py\ndofile(" + json.dumps(str(root / "hyprland/hyprland.lua"), ensure_ascii=False) + ")\n",
        config / "hypr/hyprlock.conf": root / "hyprland/hyprlock.conf",
        config / "hypr/hypridle.conf": root / "hyprland/hypridle.conf",
        config / "xdg-desktop-portal/hyprland-portals.conf": root / "hyprland/portals.conf",
    }
    if manifest.exists():
        existing = json.loads(manifest.read_text())
        if existing["root"] == str(root) and all(fingerprint(Path(entry["path"])) == entry["installed"] for entry in existing["files"]):
            return
        raise ValueError("A development setup already exists or was edited; teardown it before reinstalling.")
    for path in files:
        backup = path.with_name(path.name + ".before-zephyrus")
        if backup.exists() or backup.is_symlink() or (path.exists() and not path.is_file() and not path.is_symlink()):
            raise ValueError("An existing backup or non-file blocks setup: " + str(path))
    entries = []
    try:
        for path, content in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            backup = path.with_name(path.name + ".before-zephyrus")
            existed = path.exists() or path.is_symlink()
            if existed:
                path.rename(backup)
            entry = {"path": str(path), "backup": str(backup) if existed else None}
            entries.append(entry)
            if isinstance(content, Path):
                path.symlink_to(content)
            else:
                path.write_text(content)
            entry["installed"] = fingerprint(path)
        manifest.parent.mkdir(parents=True, exist_ok=True)
        manifest.write_text(json.dumps({"root": str(root), "files": entries}, indent=2) + "\n")
    except BaseException:
        for entry in reversed(entries):
            path = Path(entry["path"])
            path.unlink(missing_ok=True)
            if entry["backup"]:
                Path(entry["backup"]).rename(path)
        raise


def teardown(state):
    manifest = state / "zephyrus-shell/dev-session.json"
    if not manifest.exists():
        raise ValueError("No development setup is recorded.")
    data = json.loads(manifest.read_text())
    for entry in data["files"]:
        if fingerprint(Path(entry["path"])) != entry["installed"]:
            raise ValueError("An installed file was edited; preserve it and resolve before teardown: " + entry["path"])
        if entry["backup"] and not (Path(entry["backup"]).exists() or Path(entry["backup"]).is_symlink()):
            raise ValueError("A recorded backup is missing; teardown stopped.")
    for entry in reversed(data["files"]):
        path = Path(entry["path"])
        path.unlink()
        if entry["backup"]:
            Path(entry["backup"]).rename(path)
    manifest.unlink()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("install", "teardown"))
    args = parser.parse_args()
    config = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
    state = Path(os.environ.get("XDG_STATE_HOME", Path.home() / ".local/state"))
    try:
        if args.action == "install":
            install(config, state)
            sync_lock_background(config)
        else:
            teardown(state)
        print("Development session " + args.action + " complete.")
    except (OSError, ValueError, KeyError) as error:
        print(str(error), file=sys.stderr)
        sys.exit(1)
