#!/usr/bin/env python3
"""Install reversible user session configuration for a checkout or package."""

import argparse
import hashlib
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SYSTEM_ROOT = Path("/usr/share/zephyrus-shell")
sys.path.insert(0, str(ROOT))
from services.wallpaper import sync_lock_background


def fingerprint(path):
    if path.is_symlink():
        return "link:" + os.readlink(path)
    if path.is_file():
        return "file:" + hashlib.sha256(path.read_bytes()).hexdigest()
    return None


def session_files(config, root=ROOT):
    """Return managed files (text or symlink target) and editable seed defaults."""
    root = Path(root)
    files = {
        config / "hypr/hyprland.lua": "-- Generated by Zephyrus setup-session.py\ndofile("
        + json.dumps(str(root / "hyprland/hyprland.lua"), ensure_ascii=False)
        + ")\n",
        config / "hypr/hyprlock.conf": root / "hyprland/hyprlock.conf",
        config / "hypr/hypridle.conf": root / "hyprland/hypridle.conf",
        config / "xdg-desktop-portal/hyprland-portals.conf": root / "hyprland/portals.conf",
    }
    # Use systemd's native service restart and session cleanup. Escape systemd
    # specifiers and quoted ExecStart arguments for arbitrary checkout paths.
    unit_root = str(root).replace("%", "%%").replace("\\", "\\\\").replace('"', '\\"')
    if "\n" in unit_root or "\r" in unit_root:
        raise ValueError("Checkout path must not contain a newline")
    user_units = config / "systemd/user"
    files[user_units / "zephyrus-shell.service"] = (
        (ROOT / "systemd/user/zephyrus-shell.service.in").read_text().replace("@ROOT@", unit_root)
    )
    files[user_units / "hypridle.service.d/idle-policy.conf"] = (
        (ROOT / "systemd/user/idle-policy.conf.in").read_text().replace("@ROOT@", unit_root)
    )
    for unit in ("hypridle", "hyprpolkitagent"):
        files[user_units / (unit + ".service.d/zephyrus.conf")] = (
            ROOT / "systemd/user/hyprland-only.conf"
        )
        files[user_units / ("graphical-session.target.wants/" + unit + ".service")] = Path(
            "/usr/lib/systemd/user"
        ) / (unit + ".service")
    files[user_units / "graphical-session.target.wants/zephyrus-shell.service"] = Path(
        "../zephyrus-shell.service"
    )
    files[user_units / "zephyrus-clipboard@.service"] = (
        ROOT / "systemd/user/zephyrus-clipboard@.service"
    )
    for kind in ("text", "image"):
        files[user_units / f"graphical-session.target.wants/zephyrus-clipboard@{kind}.service"] = (
            Path("../zephyrus-clipboard@.service")
        )
    # Seeds become ordinary user configuration: written only when missing and
    # never removed, since theme sync and applications edit them afterwards.
    seeds = {config / name: ROOT / "desktop/defaults" / name for name in ("dolphinrc", "kdeglobals")}
    return files, seeds


def write(path, content):
    if isinstance(content, Path):
        path.symlink_to(content)
    else:
        path.write_text(content)


def provision(config, root=ROOT, strategies=None):
    """Generate skeleton defaults; the caller owns reconciliation into home."""
    files, seeds = session_files(config, root)
    for path, content in {**files, **seeds}.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = path.with_name(path.name + ".zephyrus-tmp")
        temporary.unlink(missing_ok=True)
        write(temporary, content.read_text() if path in seeds else content)
        temporary.replace(path)
    if strategies:
        # Public output lets consumers retain generated configs without knowing
        # the shell's file layout. Editable defaults preserve user edits.
        with Path(strategies).open("a") as output:
            for path in {**files, **seeds}:
                mode = "unchanged" if path in seeds else "never"
                output.write(f"{path.relative_to(config.parent)}\treplace\t{mode}\n")


def check(config, root=ROOT):
    files, seeds = session_files(config, root)
    for path in seeds:
        if not path.is_file():
            raise ValueError("Missing session default: " + str(path))
    for path, content in files.items():
        if isinstance(content, Path):
            if not path.is_symlink() or os.readlink(path) != str(content):
                raise ValueError("Incorrect session link: " + str(path))
        elif not path.is_file() or path.read_text() != content:
            raise ValueError("Incorrect session configuration: " + str(path))


def install(config, state, root=ROOT):
    root = Path(root)
    manifest = state / "zephyrus-shell/dev-session.json"
    files, seeds = session_files(config, root)
    previous_entries = []
    if manifest.exists():
        existing = json.loads(manifest.read_text())
        previous_entries = existing["files"]
        installed = {entry["path"] for entry in previous_entries}
        if existing["root"] != str(root) or not all(
            fingerprint(Path(entry["path"])) == entry["installed"] for entry in previous_entries
        ):
            raise ValueError(
                "A development setup for another checkout exists or was edited; teardown it before reinstalling."
            )
        # Add newly supported files to an unchanged installation without
        # tearing down its active graphical session or losing recovery data.
        # Entries for files no longer generated stay recorded for teardown.
        files = {path: content for path, content in files.items() if str(path) not in installed}
    for path, template in seeds.items():
        if not (path.exists() or path.is_symlink()):
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(template.read_text())
    if not files:
        return
    for path in files:
        backup = path.with_name(path.name + ".before-zephyrus")
        if (
            backup.exists()
            or backup.is_symlink()
            or (path.exists() and not path.is_file() and not path.is_symlink())
        ):
            raise ValueError("An existing backup or non-file blocks setup: " + str(path))
    entries = []
    try:
        for path, content in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            backup = path.with_name(path.name + ".before-zephyrus")
            existed = path.exists() or path.is_symlink()
            if existed:
                path.rename(backup)
            entry = {"path": str(path), "backup": str(backup) if existed else None}
            entries.append(entry)
            write(path, content)
            entry["installed"] = fingerprint(path)
        manifest.parent.mkdir(parents=True, exist_ok=True)
        manifest.write_text(
            json.dumps({"root": str(root), "files": previous_entries + entries}, indent=2) + "\n"
        )
    except BaseException:
        for entry in reversed(entries):
            path = Path(str(entry["path"]))
            path.unlink(missing_ok=True)
            if entry["backup"]:
                Path(entry["backup"]).rename(path)
        raise


def teardown(state):
    manifest = state / "zephyrus-shell/dev-session.json"
    if not manifest.exists():
        raise ValueError("No development setup is recorded.")
    data = json.loads(manifest.read_text())
    for entry in data["files"]:
        if fingerprint(Path(entry["path"])) != entry["installed"]:
            raise ValueError(
                "An installed file was edited; preserve it and resolve before teardown: "
                + entry["path"]
            )
        if entry["backup"] and not (
            Path(entry["backup"]).exists() or Path(entry["backup"]).is_symlink()
        ):
            raise ValueError("A recorded backup is missing; teardown stopped.")
    for entry in reversed(data["files"]):
        path = Path(entry["path"])
        path.unlink()
        if entry["backup"]:
            Path(entry["backup"]).rename(path)
    manifest.unlink()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--system", action="store_true", help="use the installed system payload")
    parser.add_argument("action", choices=("install", "teardown", "provision", "check"))
    parser.add_argument(
        "--home-strategies",
        type=Path,
        help="append skeleton reconciliation policies (provision only)",
    )
    args = parser.parse_args()
    config = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
    state = Path(os.environ.get("XDG_STATE_HOME", Path.home() / ".local/state"))
    root = SYSTEM_ROOT if args.system else ROOT
    try:
        if args.action == "provision":
            provision(config, root, args.home_strategies)
        elif args.action == "check":
            check(config, root)
        elif args.action == "install":
            install(config, state, root)
            sync_lock_background(config)
        else:
            teardown(state)
        print("Zephyrus session " + args.action + " complete.")
    except (OSError, ValueError, KeyError) as error:
        print(str(error), file=sys.stderr)
        sys.exit(1)
